{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-command.fullname" . }}-env
  labels:
    {{- include "nexus-command.labels" . | nindent 4 }}
type: Opaque
data:
  # Database configuration - dynamically generated based on postgresql.enabled
  SPRING_DATASOURCE_URL: {{ include "nexus-command.databaseUrl" . | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ include "nexus-command.databaseUsername" . | b64enc | quote }}
  
  {{- if .Values.postgresql.enabled }}
  # Internal PostgreSQL password
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if not .Values.externalDatabase.existingSecret }}
  # External PostgreSQL password (only if not using existing secret)
  {{- if .Values.secrets.database.password }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.database.password | b64enc | quote }}
  {{- else if .Values.externalDatabase.password }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.oauth2 }}
  # OAuth2 configuration
  {{- if .Values.secrets.oauth2.clientId }}
  OAUTH2_CLIENT_ID: {{ .Values.secrets.oauth2.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oauth2.clientSecret }}
  OAUTH2_CLIENT_SECRET: {{ .Values.secrets.oauth2.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oauth2.issuerUri }}
  OAUTH2_ISSUER_URI: {{ .Values.secrets.oauth2.issuerUri | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oauth2.authorizationUri }}
  OAUTH2_AUTHORIZATION_URI: {{ .Values.secrets.oauth2.authorizationUri | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oauth2.tokenUri }}
  OAUTH2_TOKEN_URI: {{ .Values.secrets.oauth2.tokenUri | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oauth2.userInfoUri }}
  OAUTH2_USER_INFO_URI: {{ .Values.secrets.oauth2.userInfoUri | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oauth2.jwkSetUri }}
  OAUTH2_JWK_SET_URI: {{ .Values.secrets.oauth2.jwkSetUri | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.encryption }}
  # Encryption configuration
  {{- if .Values.secrets.encryption.secret }}
  NEXUS_ENCRYPTION_SECRET: {{ .Values.secrets.encryption.secret | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.mail }}
  # Mail configuration
  {{- if .Values.secrets.mail.host }}
  SPRING_MAIL_HOST: {{ .Values.secrets.mail.host | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.mail.port }}
  SPRING_MAIL_PORT: {{ .Values.secrets.mail.port | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.mail.username }}
  SPRING_MAIL_USERNAME: {{ .Values.secrets.mail.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.mail.password }}
  SPRING_MAIL_PASSWORD: {{ .Values.secrets.mail.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.mail.from }}
  SPRING_MAIL_FROM: {{ .Values.secrets.mail.from | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.ai }}
  # AI configuration
  {{- if .Values.secrets.ai.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.ai.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.google }}
  # Google Analytics configuration
  {{- if .Values.secrets.google.analyticsTrackingId }}
  GOOGLE_ANALYTICS_TRACKING_ID: {{ .Values.secrets.google.analyticsTrackingId | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- range $key, $value := .Values.secrets.custom }}
  # Custom environment variables
  {{ $key | upper }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}