= Nexus Command
:toc:
:toc-placement!:

== TLDR;
```shell
docker run -p 8080:8080 savantly/nexus-command
```


This is an link:https://causeway.apache.org[Apache Causeway] application, using best practices and conventions.  
It takes advantage of the rapid development capabilities of Causeway, and provides enterprise-grade features.  

* a domain-driven design
* a layered architecture
* a modular architecture
* a security model
* a command pattern
* a repository pattern
* a service layer
* a view model layer
* a view model factory
* a view model repository
* a view model service
* an event bus
* scheduled jobs
* rich domain APIs
* a REST API
* auditing
* exection logging
* sql logging
* session logging
* sql migrations
* automated testing
* a Docker image


It consists of:

* a "Franchise Module", which contains the domain objects and services for managing the data for a multi-site and/or franchise business.
* a "Webapp" module, which contains the bootstrapping classes, along with application-level scoped services and home page.

You can use the webapp as a starting point for your own application, or you can use the Franchise Module in your own Webapp project and customize it to your needs.  The Franchise Module is a standalone module that can be used in any webapp project.


[TIP]
====
TODO: add a link to the demo site here
====

toc::[]

== Quick start

* install prereqs:

** Java 11 LTS (eg link:https://adoptopenjdk.net/[Adopt OpenJDK] distribution)
** Maven 3.6 or later (http://maven.apache.org/download.cgi[download])
* Clone the repository:
+
[source,bash]
----
git clone git@github.com:savantly-net/nexus-command.git
# or
git clone https://github.com/savantly-net/nexus-command.git

cd nexus-command
----

* Build using Maven:
+
[source,bash]
----
mvn clean install
----

* Download the `spring-instrument.jar` for load-time weaving (discussed in more detail xref:#orm-support[below]):
+
[source,bash]
----
mvn dependency:get -DgroupId=org.springframework -DartifactId=spring-instrument -Dversion=XXX
----
+
Change "XXX" to the value that `${spring-framework.version}` resolves to in the webapp `pom.xml`

* Run using Maven:
+
[source,bash]
----
mvn -pl webapp spring-boot:run
----

* Browse to http://localhost:8080.

* Login using:

** either the secman superuser:

*** username: `secman-admin`
*** password: `pass`

** as a Nexus Command user:

*** username: `sven`
*** password: `pass`

** or as a franchisee user:

*** username: `franchisee`
*** password: `pass`

+
The app runs with H2 running in-memory, with sample data set up using fixture scripts.

* Build a Docker image
+
[source,bash]
----
export REVISION=...                 #<.>
export DOCKER_REGISTRY_USERNAME     #<.>
export DOCKER_REGISTRY_PASSWORD     #<.>

mvn -pl webapp -Ddocker jib:build
----
<.> used as the image tag
<.> Docker Hub registry username
<.> Docker Hub registry password
+
To push to another container registry, change the `<image>` tag in the pom.xml

== Application Structure

The following table explains the contents of each of the directories:

[width="100%",options="header,footer",stripes="none",cols="2a,4a"]
|====================
|Directory
|Description

|`module-franchise`
|Holds the "franchise" module, consisting of the `FranchiseLocation` entity and supporting services, among several other related entities.

[TIP]
====
Larger applications should consist of multiple modules; each such module can be copied from this starter module.
====

|`module-franchise-tests`
|Holds the unit- and integration tests for `module-franchise`.


|`webapp`
|Holds the bootstrapping classes, along with application-level scoped services and home page.

The `pom.xml` also provides goals to run the app from the command line, or to be assembled into a Docker image.

|`webapp-tests`
|Contains application-wide integration tests.

|====================

It's more common for tests to reside within the same module, but we moved them into their own Maven modules because it makes them easier to be temporarily excluded, eg during initial explorations/prototyping.


[#orm-support]
== ORM Support

This version of the application uses EclipseLink JPA as its ORM, configured with load-time weaving.
This requires that the application be run with a Java agent.

The spring-boot plugin is configured to run with this agent already.
If you want to run from an IDE:

* first, you might wish to copy the file locally:
+
[source,bash]
----
cp ~/.m2/repository/org/springframework/spring-instrument/XXX/spring-instrument-XXX.jar lib/spring-instrument.jar
----
+
Change "XXX" to the value that `${spring-framework.version}` resolves to in the webapp `pom.xml`

* Then specify the agent as a VM option:
+
[source,bash]
----
-javaagent:lib/spring-instrument.jar
----

== Testing

The application has both unit tests and integration tests.

.Testing types
[cols="5a,12a,6a,3a", options="header"]
|===

| Test type
| Report
| Phase
| Skip using

| Unit test
| `target/surefire-unittest-reports`
| `test`
| `-DskipUTs`

| Integ test
| `target/surefire-integtest-reports`
| `integration-test`
| `-DskipITs`


|===


These outputs can for example be processed within/published by a continuous pipeline.



== Translations

Apache Causeway supports i18n using link:https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html[GNU .po file]s.
The `WEB-INF/translations.po` is the fallback (an empty value means that the key is used "as-is"), while `WEB-INF/translations-XX.po` files provide translations for each "XX" locale.

Translations are required for all domain classes and all members (actions, properties and collections) of all classes.
This information is available from the metamodel, and so a new template `translations.po` is generated as a side effect of running the integration tests (through a log4j2 logger).
A good integration test to run is `ValidateDomainModel_IntegTest`.

In addition, translations are required for any validation messages triggered by the test.
Running an integration tests that trigger validations will result in these messages being captured as keys, for example `Smoke_IntegTest`.

The generated file should be merged with any existing translations in `WEB-INF/translations.po`, and translations obtained for any new keys (there are numerous online services that support the format).


== Flyway

The application also demonstrates how to use Flyway to migrate the database schema.

By default the app runs using an in-memory database.
The Flyway example is activated using the "SQLSERVER" Spring Boot profile, eg:

[source,bash]
----
mvn -Dspring.profiles.active=SQLSERVER -pl webapp install
mvn -Dspring.profiles.active=SQLSERVER -pl webapp spring-boot:run
----

This causes the properties defined in  `config/application-SQLSERVER.properties` file to be used in preference to those in the default `config/application.properties` file.
It defines the following:

* `spring.flyway.url`, `spring.flyway.user` and `spring.flyway.password`
+
The presence of these is enough to enable the Flyway integration

* `spring.flyway.enabled`
+
This is explicitly set to `true`, to override the value in the default `config/application.properties`.

* `causeway.persistence.jdo-datanucleus.impl.datanucleus.schema.autoCreateAll`
+
This is set to `false`, also overriding the value in the default `config/application.properties`.
It instructs the JDO/DataNucleus object store not to automatically create any tables etc.

The Spring Boot profile is also used to add the dependency to the SQL Server driver is included (it is hidden behind a Maven profile).

The prerequisites to try this out are a SQL Server database running on `localhost` and with the credentials as specified in `config/application-SQLSERVER.properties`; adjust as necessary.

